version: '3'
services:
  face_recognition:
    container_name: "face_recognition"
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    build: .
    environment:
      - DATABASE_URI=mongodb://admin:password@mongo:27017
      - FACE_TOLERANCE=0.6
    ports:
      - "5000:5000"
  mongo:
    container_name: "mongo"
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  schedule:
    container_name: "schedule"
    restart: always
    links:
      - mongo
    depends_on:
      - mongo
    build: ./schedule
    environment:
      - DATABASE_URI=mongodb://admin:password@mongo:27017
